# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1620e99dae330acdf78047ad0f038fc581b999f13573e6e63eae406463807589fd46bf5e5a6e3bb90398b64af3b3352ac5f154b5e3928d475eef96192e80e08

test:
  secret_key_base: 2552b3358a88a159951bfa6025dc92c3f723ed18ac8979491eee53d539e1f432603b8b0aeb8fd4670cc7abccb55c53535083cee6a15d90532390cb4570f51d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
